version: "3.8"

#docker run --rm -p3306:3306 -eMYSQL_ALLOW_EMPTY_PASSWORD=true mysql
services:
  app:
    #image: ignotasburba/logger-app:1.0
    build:
      context: ./Logger
      dockerfile: Dockerfile
    ports:
      - 3308:3306
    depends_on:
      mysql:
        condition: service_healthy
    links: 
        - mysql
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  mysqldb:
networks:
  default: